### ISSUE TITLE
NotFound Exception

### ISSUE THREAD

**Issue by kdubuc** [1ma/DIC#1]
Hi !

What about a NotFoundException ? 

When I try to ```get``` with a wrong idea, I have a strange error like "_class@anonymous\/DIR/vendor/uma/dic/src/Container.php0x7fecee803266_" because of the ```call_user_func```.

If you want, I can make a PR.

**Comment by 1ma** [comment]
Yes, it's because I didn't bother to define an Exception class and used an anonymous object instead (see https://github.com/1ma/DIC/blob/master/src/Container.php#L68).

I agree that the error message is very cryptic, but the implementation fulfills the PSR-11 contract. Feel free to submit a PR if you want.

**Comment by kdubuc** [comment]
Ok, good for me, thanks !
